name: fireuser
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:
  firebase_core: ^0.7.0
  firebase_analytics: ^7.0.1
  firebase_auth: ^0.20.1
  firebase_auth_web: ^0.3.3
  cloud_firestore: ^0.16.0+1
  http: ^0.12.0
  cupertino_icons: ^1.0.2
  flutter_blue: ^0.7.3
  intl: ^0.16.1
  connectivity: ^2.0.2
  cron: 0.2.4
  flutter_ringtone_player: 2.0.0
  wakelock: ^0.2.1+1
  bloc: ^6.1.1
  flutter_bloc: ^6.1.2
  equatable: ^1.2.6
  flutter_spinkit: ^4.1.2+1

flutter:
  uses-material-design: true
  assets:
    - images/